<!DOCTYPE html><html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en"><head><title></title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]--><style>
*{box-sizing:border-box}body{margin:0;padding:0}a[x-apple-data-detectors]{color:inherit!important;text-decoration:inherit!important}#MessageViewBody a{color:inherit;text-decoration:none}p{line-height:inherit}.desktop_hide,.desktop_hide table{mso-hide:all;display:none;max-height:0;overflow:hidden}@media (max-width:670px){.desktop_hide table.icons-inner{display:inline-block!important}.icons-inner{text-align:center}.icons-inner td{margin:0 auto}.image_block img.big,.row-content{width:100%!important}.mobile_hide{display:none}.stack .column{width:100%;display:block}.mobile_hide{min-height:0;max-height:0;max-width:0;overflow:hidden;font-size:0}.desktop_hide,.desktop_hide table{display:table!important;max-height:none!important}}
</style></head><body style="background-color:#3d1554;margin:0;padding:0;-webkit-text-size-adjust:none;text-size-adjust:none"><table class="nl-container" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#3d1554"><tbody><tr><td><table class="row row-1" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#57366e"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:650px" width="650"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" style="height:20px;line-height:20px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-2" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#57366e"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:650px" width="650"><tbody><tr><td class="column column-1" width="25%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table 
class="image_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><a href="http://www.example.com/" target="_blank" style="outline:none" tabindex="-1"><img src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/1611/logo_18.png" 
style="display:block;height:auto;border:0;width:144px;max-width:100%" width="144" alt="Logo" title="Logo"></a></div></td></tr></table></td><td class="column column-2" width="75%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:20px;padding-left:10px;padding-right:10px;padding-top:25px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#fff;line-height:1.2;font-family:Poppins,Arial,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:center">
<span style="font-size:16px;"><a style="text-decoration: none; color: #ffffff;" href="http://www.example.com/" target="_blank" rel="noopener">SHOP NOW</a>&nbsp; &nbsp;&nbsp; <a style="text-decoration: none; color: #ffffff;" href="http://www.example.com/" target="_blank" rel="noopener">REFER A FRIEND</a>&nbsp; &nbsp;&nbsp; <a style="text-decoration: none; color: #ffffff;" href="http://www.example.com/" target="_blank" rel="noopener">CONTACT US</a></span>
</p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-3" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#57366e"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:650px" width="650"><tbody><tr><td 
class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" style="height:20px;line-height:20px;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-4" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:650px" width="650"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:35px;padding-bottom:0;border-top:0;border-right:0;border-bottom:0;border-left:0"><table
 class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><img class="big" src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/1611/content-top_2.png" style="display:block;height:auto;border:0;width:650px;max-width:100%" width="650"></div></td></tr></table></td>
</tr></tbody></table></td></tr></tbody></table><table class="row row-5" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:650px" width="650"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;border-left:4px solid #57366e;border-right:4px solid #57366e;vertical-align:top;padding-top:55px;padding-bottom:60px;border-top:0;border-bottom:0"><table class="text_block block-1" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" 
style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#fbd711;line-height:1.2;font-family:Poppins,Arial,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:center"><strong><span style="font-size:30px;">ABP Framework,</span></strong></p></div></div></td></tr></table><table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" 
style="padding-bottom:10px;padding-left:50px;padding-right:50px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#fff;line-height:1.2;font-family:Poppins,Arial,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:center">
<span style="font-size:28px;">If you still wish to receive updates from us about Topic ABC, resubscribe to our newsletter <em><span style="font-size:22px;">(</span>pleaseee<span style="font-size:22px;">)</span></em></span></p></div></div></td></tr></table><table class="button_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
style="padding-bottom:12px;padding-left:10px;padding-right:10px;padding-top:12px;text-align:center"><div class="alignment" align="center">
<!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="http://www.example.com/" style="height:56px;width:221px;v-text-anchor:middle;" arcsize="54%" stroke="false" fillcolor="#fbd711"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#000000; font-family:Arial, sans-serif; font-size:18px"><![endif]-->
<a href="http://www.example.com/" target="_blank" style="text-decoration:none;display:inline-block;color:#000000;background-color:#fbd711;border-radius:30px;width:auto;border-top:1px solid #fbd711;font-weight:undefined;border-right:1px solid #fbd711;border-bottom:1px solid #fbd711;border-left:1px solid #fbd711;padding-top:10px;padding-bottom:10px;font-family:Poppins, Arial, Helvetica, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:45px;padding-right:45px;font-size:18px;display:inline-block;letter-spacing:normal;"><span style="word-break: break-word;"><span style="line-height: 36px;" data-mce-style><strong>RESUBSCRIBE</strong></span></span></span></a>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table><table class="text_block block-4" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:25px;padding-left:30px;padding-right:30px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" 
style="font-size:12px;mso-line-height-alt:18px;color:#fff;line-height:1.5;font-family:Poppins,Arial,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:center"><em>*Otherwise, we will have to remove your email address from our mailing list which will be a very sad day for us...</em></p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-6" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;background-color:#57366e;width:650px" width="650"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:30px;padding-right:30px;vertical-align:top;padding-top:55px;padding-bottom:55px;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" 
style="padding-bottom:20px;padding-left:25px;padding-right:25px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:18px;color:#fff;line-height:1.5;font-family:Poppins,Arial,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:27px">
<span style="font-size:18px;">Also to comply with the new EU privacy regulations <span style="font-size:16px;">(</span><strong>GDPR</strong><span style="font-size:16px;">)</span>, we have added a few new pages to our website:</span></p></div></div></td></tr></table><table class="button_block block-2" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad"><div class="alignment" align="center">
<!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="http://www.example.com/" style="height:61px;width:240px;v-text-anchor:middle;" arcsize="50%" strokeweight="1.5pt" strokecolor="#795E8B" fillcolor="#3d1554"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#ffffff; font-family:Arial, sans-serif; font-size:18px"><![endif]-->
<a href="http://www.example.com/" target="_blank" style="text-decoration:none;display:inline-block;color:#ffffff;background-color:#3d1554;border-radius:30px;width:auto;border-top:2px solid #795E8B;font-weight:undefined;border-right:2px solid #795E8B;border-bottom:2px solid #795E8B;border-left:2px solid #795E8B;padding-top:18px;padding-bottom:18px;font-family:Poppins, Arial, Helvetica, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:60px;padding-right:60px;font-size:18px;display:inline-block;letter-spacing:normal;"><span style="word-break: break-word;"><span style="line-height: 21.6px;" data-mce-style>Privacy Policy</span></span></span></a>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table><table class="button_block block-3" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad"><div class="alignment" align="center">
<!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="http://www.example.com/" style="height:61px;width:234px;v-text-anchor:middle;" arcsize="50%" strokeweight="1.5pt" strokecolor="#795E8B" fillcolor="#3d1554"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#ffffff; font-family:Arial, sans-serif; font-size:18px"><![endif]-->
<a href="http://www.example.com/" target="_blank" style="text-decoration:none;display:inline-block;color:#ffffff;background-color:#3d1554;border-radius:30px;width:auto;border-top:2px solid #795E8B;font-weight:undefined;border-right:2px solid #795E8B;border-bottom:2px solid #795E8B;border-left:2px solid #795E8B;padding-top:18px;padding-bottom:18px;font-family:Poppins, Arial, Helvetica, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:35px;padding-right:35px;font-size:18px;display:inline-block;letter-spacing:normal;"><span style="word-break: break-word;"><span style="line-height: 21.6px;" data-mce-style>Terms &amp; Conditions</span></span></span></a>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table><table class="button_block block-4" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad"><div class="alignment" align="center">
<!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="http://www.example.com/" style="height:61px;width:237px;v-text-anchor:middle;" arcsize="50%" strokeweight="1.5pt" strokecolor="#795E8B" fillcolor="#3d1554"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#ffffff; font-family:Arial, sans-serif; font-size:18px"><![endif]-->
<a href="http://www.example.com/" target="_blank" style="text-decoration:none;display:inline-block;color:#ffffff;background-color:#3d1554;border-radius:30px;width:auto;border-top:2px solid #795E8B;font-weight:undefined;border-right:2px solid #795E8B;border-bottom:2px solid #795E8B;border-left:2px solid #795E8B;padding-top:18px;padding-bottom:18px;font-family:Poppins, Arial, Helvetica, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:60px;padding-right:60px;font-size:18px;display:inline-block;letter-spacing:normal;"><span style="word-break: break-word;"><span style="line-height: 21.6px;" data-mce-style>Cookie Policy</span></span></span></a>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table><table class="text_block block-5" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:10px;padding-left:25px;padding-right:25px;padding-top:20px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" 
style="font-size:12px;mso-line-height-alt:18px;color:#fff;line-height:1.5;font-family:Poppins,Arial,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:24px"><span style="font-size:16px;">If you have any questions do not hesitate to <a style="text-decoration: underline; color: #ffffff;" title="hey@example.com" href="mailto:hey@example.com">reach out to us</a></span></p></div></div></td></tr></table></td></tr></tbody></table></td></tr>
</tbody></table><table class="row row-7" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:650px" width="650"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:0;padding-bottom:0;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><img class="big" 
src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/1611/content-bottom_1.png" style="display:block;height:auto;border:0;width:650px;max-width:100%" width="650"></div></td></tr></table><table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:20px;padding-left:10px;padding-right:10px;padding-top:15px"><div 
style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:18px;color:#b0a7b7;line-height:1.5;font-family:Poppins,Arial,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:18px"><span style="font-size:12px;">1600 Pennsylvania Avenue NW, Washington, DC 20500, United States</span></p><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:18px">
<span style="font-size:12px;">© Copyright 2020 Example.com</span></p><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:18px"><span style="font-size:12px;"><a style="text-decoration: none; color: #b0a7b7;" href="http://www.example.com/" target="_blank" rel="noopener">Manage Preferences</a> | <a style="text-decoration: none; color: #b0a7b7;" href="http://www.example.com/" target="_blank" rel="noopener">Unsubscribe</a></span></p></div></div></td>
</tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-8" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:650px" width="650"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="icons_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="vertical-align:middle;color:#9d9d9d;font-family:inherit;font-size:15px;padding-bottom:5px;padding-top:5px;text-align:center">
<table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="alignment" style="vertical-align:middle;text-align:center"><!--[if vml]><table align="left" cellpadding="0" cellspacing="0" role="presentation" style="display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;"><![endif]--><!--[if !vml]><!--><table class="icons-inner" 
style="mso-table-lspace:0;mso-table-rspace:0;display:inline-block;margin-right:-4px;padding-left:0;padding-right:0" cellpadding="0" cellspacing="0" role="presentation"><!--<![endif]--><tr><td style="vertical-align:middle;text-align:center;padding-top:5px;padding-bottom:5px;padding-left:5px;padding-right:6px"><a href="https://www.designedwithbee.com/" target="_blank" style="text-decoration: none;"><img class="icon" alt="Designed with BEE" 
src="https://d15k2d11r6t6rl.cloudfront.net/public/users/Integrators/BeeProAgency/53601_510656/Signature/bee.png" height="32" width="34" align="center" style="display:block;height:auto;margin:0 auto;border:0"></a></td><td style="font-family:Poppins,Arial,Helvetica,sans-serif;font-size:15px;color:#9d9d9d;vertical-align:middle;letter-spacing:undefined;text-align:center">
<a href="https://www.designedwithbee.com/" target="_blank" style="color: #9d9d9d; text-decoration: none;">Designed with BEE</a></td></tr></table></td></tr></table></td></tr></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!-- End --></body></html>